# Package
version = "0.1.0"
author = "Roni"
description = "A computer graphics project in Nim and OpenGL"
srcDir = "src"
binDir = "bin"
namedBin["SdfRenderer"] = "sdf-renderer"
namedBin["SdfRendererGl"] = "sdf-renderer-gl"
namedBin["SdfRendererFragment"] = "sdf-renderer-fragment"
namedBin["BasicVulkan"] = "basic-vulkan"
namedBin["../tests/TestCheckpoint1"] = "test-checkpoint1"
namedBin["../tests/TestCheckpoint2"] = "test-checkpoint2"
namedBin["../tests/TestCheckpoint4"] = "test-checkpoint4"
backend = "c"
license = "MIT"

# Dependencies
requires "nim >= 2.2.10"
requires "confutils"
requires "jsony"
requires "vmath"
requires "https://github.com/stavenko/nim-glm#47d5f8681f3c462b37e37ebc5e7067fa5cba4d16"
requires "https://github.com/nim-lang/sdl3.git"
requires "https://github.com/treeform/vk14.git"
